id: P008006
initial_creation_type: ocr
created_at: 24/03/2020
last_modified_at: 2021-12-17 12:54:40.919313
source_metadata:
  id: bdr:W1KG15822
  title: སྤྱོད་འཇུག་རྩ་འགྲེལ་ཆེན་མོ། ༼གློག་ཀླད་པར་མ།༽
  author: ''
  volumes:
    732fec13102c4fc7998606073f2ab554:
      image_group_id: I1KG15824
      title: Volume 1 of spyod 'jug rtsa 'grel chen mo/ (glog klad par ma/)
      volume_number: 1
      total_pages: 634
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
