id: P008006
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG15822
  title: སྤྱོད་འཇུག་རྩ་འགྲེལ་ཆེན་མོ། ༼གློག་ཀླད་པར་མ།༽
  author: ''
  volumes:
    dc93002a158f486094a72822ba1ae4e8:
      image_group_id: I1KG15824
      title: ''
      volume_number: 1
      total_pages: 634
ebook_metadata:
  title: སྤྱོད་འཇུག་རྩ་འགྲེལ་ཆེན་མོ། ༼གློག་ཀླད་པར་མ།༽
  author: ''
  sku: P008006
  cover: cover.jpg
  layers:
  - pagination
